# Generated by Django 5.0.1 on 2024-11-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_generator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentprocessingjob",
            name="video_length",
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="video_preference",
            field=models.TextField(default="simplify"),
            preserve_default=False,
        ),
    ]
