# Generated by Django 5.0.1 on 2024-11-14 08:31

import video_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0003_remove_documentprocessingjob_processing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprocessingjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=video_generator.models.upload_to_unique_filename),
        ),
    ]
