# Generated by Django 5.0.1 on 2024-11-15 22:04

import video_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_generator", "0004_alter_documentprocessingjob_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoprocessingjob",
            name="document_job",
        ),
        migrations.RemoveField(
            model_name="videoprocessingjob",
            name="video_length",
        ),
        migrations.RemoveField(
            model_name="videoprocessingjob",
            name="video_preview",
        ),
        migrations.AddField(
            model_name="video",
            name="visemes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videoprocessingjob",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=video_generator.models.upload_to_unique_filename,
            ),
        ),
        migrations.AddField(
            model_name="videoprocessingjob",
            name="language",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videoprocessingjob",
            name="script",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videoprocessingjob",
            name="video_preference",
            field=models.TextField(default="simplify"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DocumentProcessingJob",
        ),
    ]
